### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by iMpr0** [Taqhee/BTC_TradingBot#1]
I got this error while running the script:

Traceback (most recent call last):
  File "bot.py", line 142, in <module>
    if last - breakEvenPrice > 15:            
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by Taqhee** [comment]
You might be getting this error because you might have open positions in more than one instrument. 

Line 141 in "bot.py"
`breakEvenPrice = mexorders.get_positions()[0]['breakEvenPrice']` returns the breakeven price of the positions which appears first (XBTU18 appears before XBTUSD)

Run
`mexorders.get_positions()` to determine the index of the instrument "XBTUSD" and 

modify line 141 to  
`breakEvenPrice = mexorders.get_positions()[1]['breakEvenPrice']`.

Please let me know if that helps
